C300Project/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace fyp.Models
{
    public partial class Question
    {
        public Question()
        {
            QuizQuestionBindDb = new HashSet<QuizQuestionBindDb>();
        }

        public int QuestionId { get; set; }
        [Required(ErrorMessage = "Question Required")]
        public string Questions { get; set; }
        [Required(ErrorMessage = "Option Required")]
        public string FirstOption { get; set; }
        [Required(ErrorMessage = "Option Required")]
        public string SecondOption { get; set; }
        [Required(ErrorMessage = "Option Required")]
        public string ThirdOption { get; set; }
        [Required(ErrorMessage = "Option Required")]
        public string FourthOption { get; set; }
        [Required(ErrorMessage = "Topic Required")]
        public int Topic { get; set; }
        [Required(ErrorMessage = "Correct Answer Required")]
        public string CorrectAns { get; set;}
        [Required(ErrorMessage = "Segment Required")]
        public int? Segment { get; set; }
        public string UserCode { get; set; }

        public virtual Segment SegmentNavigation { get; set; }
        public virtual Topic TopicNavigation { get; set; }
        public virtual Account UserCodeNavigation { get; set; }
        public virtual ICollection<QuizQuestionBindDb> QuizQuestionBindDb { get; set; }
    }
}

C300Project/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using fyp.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Web;

namespace fyp.Controllers
{
    public class QuestionsController : Controller
    {
        private AppDbContext _dbContext;

        public QuestionsController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        #region Index Action
        public IActionResult Index()
        {
            DbSet<Question> dbs = _dbContext.Question;
            List<Question> model = dbs
                .Include(mo => mo.SegmentNavigation)
                .Include(mo => mo.TopicNavigation)
                .ToList();

            if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                model = dbs.Include(mo => mo.UserCodeNavigation)
                            .ToList();
            else
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                model = dbs.Where(so => so.UserCode == userId).ToList();
            }

            DbSet<Topic> dbs3 = _dbContext.Topic;
            var lstTopic = dbs3.ToList();
            ViewData["Topic"] = new SelectList(lstTopic, "TopicId", "Name");

            return View(model);

        }
        #endregion

        #region Create Get Action
        [Authorize(Roles = "Admin,Teacher")]
        public IActionResult Create()
        {
            
            DbSet<Quiz> dbs = _dbContext.Quiz;
            var lstQuiz = dbs
                .Include(mo => mo.TopicNavigation)
                .ToList();
            
            DbSet<Segment> dbs2 = _dbContext.Segment;
            var lstSegment = dbs2.ToList();
            ViewData["Segment"] = new SelectList(lstSegment, "SegmentId", "Name");

            DbSet<Topic> dbs3 = _dbContext.Topic;
            var lstTopic = dbs3.ToList();
            ViewData["Topic"] = new SelectList(lstTopic, "TopicId", "Name");
            return View();
        }
        #endregion

        #region Create Post Action
        [Authorize(Roles = "Admin,Teacher")]
        [HttpPost]
        public IActionResult Create(Question question, IFormCollection form)
        {
            DbSet<Question> dbs = _dbContext.Question;
            DbSet<Quiz> dbs2 = _dbContext.Quiz;
            DbSet<QuizQuestionBindDb> dbs3= _dbContext.QuizQuestionBindDb;

            List<Quiz> lstQuiz = dbs2.ToList();
            var dbcount = lstQuiz.Count();

            question.UserCode = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (ModelState.IsValid)
            {   
                
                dbs.Add(question);
                _dbContext.SaveChanges();
                for (var x = 0; x < dbcount; x++)
                    {

                    QuizQuestionBindDb quizQuestionBind = new QuizQuestionBindDb();
                    var y = x + 1;
                    var radiocheck = Convert.ToInt32(form["Add" + y]);
                        
                    if (radiocheck > 0)
                    {
                        if (ModelState.IsValid)
                            {
                            quizQuestionBind.QuestionId = question.QuestionId;
                            quizQuestionBind.QuizId = radiocheck;
                            dbs3.Add(quizQuestionBind);
                            }
                    }  
                }
                if (_dbContext.SaveChanges() >= 1)
                    TempData["Msg"] = "New question added!";    
                    
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region Update Get Action
        [Authorize]
        public IActionResult Update(int id)
        {
            DbSet<Question> dbs = _dbContext.Question;
            DbSet<QuizQuestionBindDb> dbs2 = _dbContext.QuizQuestionBindDb;
            DbSet<Quiz> dbs3 = _dbContext.Quiz;
            DbSet<Segment> dbs4 = _dbContext.Segment;
            DbSet<Topic> dbs5 = _dbContext.Topic;

            var lstTopic = dbs5.ToList();
            

            List<QuizQuestionBindDb> lstdb2 = dbs2.Where(mo => mo.QuestionId == id).ToList();
            List<Question> lstdb = dbs.ToList();
            var lstSegment = dbs4.ToList();

            List<int> lstoverlap = lstdb2.Select(mo => mo.QuizId).ToList();
            List<int> lstdb3 = dbs3.Select(mo => mo.QuizId).ToList();
            List<int> commonlist = lstoverlap.Intersect(lstdb3).ToList();
            
            Question question = dbs
                .Where(mo => mo.QuestionId == id)
                .Include(mo => mo.SegmentNavigation)
                .Include(mo => mo.TopicNavigation).FirstOrDefault();

            
            

            if (question != null)
            {
                DbSet<Quiz> dbsQuiz = _dbContext.Quiz;
                var lstQuiz = dbsQuiz.ToList();
                ViewData["Topic"] = new SelectList(lstTopic, "TopicId", "Name");
                ViewData["Segment"] = new SelectList(lstSegment, "SegmentId", "Name");
                ViewData["common"] = commonlist;
                return View(question);
            }
            else
            {
                TempData["Msg"] = "Question not found!";
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Update Post Action
        [Authorize]
        [HttpPost]
        public IActionResult Update(Question question, IFormCollection form)
        {
            if (ModelState.IsValid)
            {
                DbSet<Question> dbs = _dbContext.Question;
                DbSet<QuizQuestionBindDb> dbs2 = _dbContext.QuizQuestionBindDb;
                DbSet<Quiz> dbs3 = _dbContext.Quiz;

                Question tOrder = dbs.Where(mo => mo.QuestionId == question.QuestionId).FirstOrDefault();

                
                List<Quiz> lstQuiz = dbs3.ToList();
                List<QuizQuestionBindDb> lstdb2 = dbs2.Where(mo => mo.QuestionId == question.QuestionId).ToList();
                var dbcount = lstQuiz.Count();

                List<int> lstoverlap = lstdb2.Select(mo => mo.QuizId).ToList();
                List<int> lstdb3 = dbs2.Select(mo => mo.QuizId).ToList();
                List<int> commonlist = lstoverlap.Intersect(lstdb3).ToList();

                for (var x = 0; x < dbcount; x++)
                {

                    QuizQuestionBindDb quizQuestionBind = new QuizQuestionBindDb();
                    var y = x + 1;
                    var quizcheck = Convert.ToInt32(form["currAddId" + y]);
                    var radiocheck = Convert.ToInt32(form["Add" + y]);

                    if(commonlist.Contains(quizcheck) && radiocheck == -1)
                    {
                        dbs2.Remove(dbs2.Where(mo =>mo.QuestionId == question.QuestionId && mo.QuizId == quizcheck).FirstOrDefault());
                    }else if (commonlist.Contains(quizcheck) && radiocheck > 0)
                    {
                        continue;
                    }
                    else if (radiocheck > 0)
                    {
                        if (ModelState.IsValid)
                        {
                            quizQuestionBind.QuestionId = question.QuestionId;
                            quizQuestionBind.QuizId = radiocheck;
                            dbs2.Add(quizQuestionBind);

                        }
                    }

                }

                if (tOrder != null)
                {
                    tOrder.Questions = question.Questions;
                    tOrder.FirstOption = question.FirstOption;
                    tOrder.SecondOption = question.SecondOption;
                    tOrder.ThirdOption = question.ThirdOption;
                    tOrder.FourthOption = question.FourthOption;
                    tOrder.Topic = question.Topic;
                    tOrder.Segment = question.Segment;
                    tOrder.CorrectAns = question.CorrectAns;

                    if (_dbContext.SaveChanges() >= 1)
                        TempData["Msg"] = "Question updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Question not found!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region Delete Action
        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<Question> dbs = _dbContext.Question;
            DbSet<QuizQuestionBindDb> dbs2 = _dbContext.QuizQuestionBindDb;

            dbs2.RemoveRange(dbs2.Where(mo => mo.QuestionId == id).ToList());
            _dbContext.SaveChanges();

            Question tOrder = dbs.Where(mo => mo.QuestionId== id)
                                     .FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);
                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Question deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Question not found!";
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region GetQtns

C300Project/Views/Questions/Create.cshtml
@model Question

@{
    ViewBag.Title = "Create new question!";
}

@section ScriptSection {

    
    <script>
        function ConfirmCreate() {
            if (confirm("Confirm create Question?") == false) {
                event.preventDefault();
                event.stopPropagation();
                return false;

            }
        }

        function LoadQuizAddTable(quizId) {
            var url = "/Quiz/GetQuizTableAdd?quizId=" + quizId;

            $("#divQuizTableAdd").html("");
            $("#divQuizTableAdd").load(url);
        }

        $(document).ready(function () {

            $("#QuizSelect").change(function () {
                var quizId = $("#QuizSelect").val();
                LoadQuizAddTable(quizId);
            });

            LoadQuizAddTable(-1);
        })

    </script>
}


    <h2>@ViewData["Title"]</h2>

    <div class="row">
        <div class="col-sm-7">
            <span style="color:red">@ViewData["Msg"]</span><br />
            <form asp-controller="Questions" asp-action="Create" method="post" class="form-horizontal" role="form">
                <div class="form-horizontal">
                    <partial name="_Questions" />

                    <div class="col-sm-6">
                        Quiz Topic:
                        <select id="QuizSelect" name="QuizSelect" asp-items="@((SelectList)ViewData["Topic"])" class="form-control">
                            <option value="-1">All</option>
                        </select>
                    </div>

                    <div id="divQuizTableAdd">
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <input type="submit" value="Create" class="btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

C300Project/Views/Questions/Index.cshtml
@model List<Question>

@{
    ViewBag.Title = "Questions";
}

@section ScriptSection {

    <script>
        function ConfirmDelete() {
            if (confirm("Are you sure you want to delete?") == false) {
                event.preventDefault();
                event.stopPropagation();
                return false;

            }
        }

        function LoadQtns(moduleId) {
            var url = "/Questions/GetQtns?moduleId=" + moduleId;

            $("#divQtnIndex").html("");
            $("#divQtnIndex").load(url);
        }

        $(document).ready(function () {

            $("#QtnSelect").change(function () {
                var moduleId = $("#QtnSelect").val();
                LoadQtns(moduleId);
            });

            LoadQtns(-1);
        })

    </script>
}

<h2>Question Bank</h2>

<span style="color:red">@TempData["Msg"]</span>
<br />
<p>
    <a asp-controller="Questions" asp-action="Create">Create New Question</a>
</p>

<div class="tab-content" style="margin-top:10px">
    <div class="col-sm-6">
        <select id="QtnSelect" asp-items="@((SelectList)ViewData["Topic"])" class="form-control">
            <option value="-1">All</option>
        </select>
    </div>

    <div id="divQtnIndex">
    </div>
    
</div>


<h2> test github</h2>

C300Project/Views/Questions/Update.cshtml
@model Question

@{
    ViewBag.Title = "Update Question!";
}

@section ScriptSection {


<script>
    function ConfirmUpdate() {
        if (confirm("Are you sure you want to delete?") == false) {
            event.preventDefault();
            event.stopPropagation();
            return false;

        }
    }


    function LoadQuizUpdateTable(quizId, questionId) {
        var url = "/Quiz/GetQuizTableUpdate?quizId=" + quizId + "&questionId=" + questionId;

        $("#divUpdateQuiz").html("");
        $("#divUpdateQuiz").load(url);
    }

    $(document).ready(function () {
        var qId = $("#questId").val();


        $("#QuizSelect").change(function () {
            var quizId = $("#QuizSelect").val();
            LoadQuizUpdateTable(quizId, qId);
        });

        LoadQuizUpdateTable(-1, qId);
    })

</script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <span style="color:red">@ViewData["Msg"]</span><br />
        <div class="container">

            <form asp-controller="Questions" asp-action="Update" method="post" class="form-horizontal" role="form">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label asp-for="QuestionId" class="col-sm-3 control-label">Question Id: </label>
                        <div class="col-sm-6">
                            <input id="questId" asp-for="QuestionId" class="form-control" readonly="readonly" />
                        </div>
                        <div class="has-error">
                            <span asp-validation-for="QuestionId" class="text-danger"></span>
                        </div>
                    </div>

                    <partial name="_Questions" />

                    <div class="col-sm-6">
                        Quiz Topic:
                        <select id="QuizSelect" name="QuizSelect" asp-items="@((SelectList)ViewData["Topic"])" class="form-control">
                            <option value="-1">All</option>
                        </select>
                    </div>

                    <div id="divUpdateQuiz">
                    </div>


                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <input type="submit" value="Update" class="btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
 </div>