C300Project/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace fyp.Models
{
    public partial class Teacher
    {
        public Teacher()
        {
            TeacherClassBindDb = new HashSet<TeacherClassBindDb>();
            TeacherStudentBindDb = new HashSet<TeacherStudentBindDb>();
        }

        public int TeacherId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string AddedBy { get; set; }

        public virtual Account AddedByNavigation { get; set; }
        public virtual ICollection<TeacherClassBindDb> TeacherClassBindDb { get; set; }
        public virtual ICollection<TeacherStudentBindDb> TeacherStudentBindDb { get; set; }
    }
}

C300Project/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fyp.Models;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;

namespace fyp.Controllers
{
    public class TeacherController : Controller
    {
        private AppDbContext _dbContext;
        public TeacherController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        #region Teacher Index
        //Main page that will show teachers and their details
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            DbSet<Teacher> dbs = _dbContext.Teacher;
            List<Teacher> model = dbs.Include(m=> m.AddedByNavigation).ToList();
            
            return View(model);
        }
        #endregion Teacher Index

        #region HttpGet Create Teacher Action
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            DbSet<Class> dbs = _dbContext.Class;
            var lstClass = dbs.ToList();
            ViewData["Class"] = lstClass;
            return View();
        }
        #endregion

        #region HttpPost Create Teacher Action
        //HttpPost Action to create a new teacher object and send to Teacher database
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Teacher teacher,IFormCollection form)
        {
            DbSet<Teacher> dbsteach = _dbContext.Teacher;
            

            DbSet<Class> dbsclass = _dbContext.Class;
            List<Class> lstClass = dbsclass.ToList();
            var dbcount = lstClass.Count();

            DbSet<Student> dbsstudent = _dbContext.Student;

            DbSet<TeacherClassBindDb> dbsTchCls = _dbContext.TeacherClassBindDb;
            DbSet<StudentClassBindDb> dbsStdCls = _dbContext.StudentClassBindDb;
            DbSet<TeacherStudentBindDb> dbsTchStd = _dbContext.TeacherStudentBindDb;

            if (ModelState.IsValid)
            {
                teacher.AddedBy = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                dbsteach.Add(teacher);
                _dbContext.SaveChanges();
                for (var x = 0; x < dbcount; x++)
                {

                    TeacherClassBindDb teacherClassBindDb = new TeacherClassBindDb();
                    var y = x + 1;
                    var radiocheck = Convert.ToInt32(form["Add" + y]);

                    if (radiocheck > 0)
                    {
                        if (ModelState.IsValid)
                        {
                            teacherClassBindDb.TeacherId = teacher.TeacherId;
                            teacherClassBindDb.ClassId = radiocheck;


                            List<StudentClassBindDb> lstStdcls = 
                                dbsStdCls.
                                Where(m => m.ClassId == y)
                                .ToList();

                            List<Student> lstStd = dbsstudent
                                .Where(m => lstStdcls
                                .Select(m => m.StudentId)
                                .Contains(m.StudentId))
                                .ToList();

                            #region Add entry to TeacherStudentBindDb  
                            if (lstStd != null)
                            {
                                foreach(var item in lstStd)
                                {
                                    TeacherStudentBindDb dbsTchStdAdd = new TeacherStudentBindDb();
                                    dbsTchStdAdd.StudentId = item.StudentId;
                                    dbsTchStdAdd.TeacherId = teacher.TeacherId;

                                    dbsTchStd.Add(dbsTchStdAdd);
                                    
                                }
                                _dbContext.SaveChanges();
                            }
                            else
                            {
                                continue;
                            }
                                
# endregion Add entry to TeacherStudentBindDb  

                            dbsTchCls.Add(teacherClassBindDb);

                        }
                    }

                }
                if (_dbContext.SaveChanges() >= 1)
                    TempData["Msg"] = "New teacher added!";

                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }
        #endregion HttpPost Create Teacher Action

        #region HttpGet Update Teacher Action
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Update(int id)
        {
            DbSet<TeacherClassBindDb> dbs2 = _dbContext.TeacherClassBindDb;
            List<TeacherClassBindDb> lstdb2 = dbs2.Where(mo => mo.TeacherId == id).ToList();
            List<int> lstoverlap = lstdb2.Select(mo => mo.ClassId).ToList();
            DbSet<Class> dbs3 = _dbContext.Class;
            List<int> lstdb3 = dbs3.Select(mo => mo.ClassId).ToList();
            DbSet<Teacher> dbs = _dbContext.Teacher;
            List<Teacher> lstdb = dbs.ToList();
            Teacher teacher = dbs.Where(mo => mo.TeacherId == id).FirstOrDefault();

            List<int> commonlist = lstoverlap.Intersect(lstdb3).ToList();

            if (teacher != null)
            {
                var lstClass = dbs3.ToList();
                ViewData["Test"] = lstClass;
                ViewData["common"] = commonlist;
                return View(teacher);
            }
            else
            {
                TempData["Msg"] = "Question not found!";
                return RedirectToAction("Index");
            }
        }
        #endregion HttpPost Create Teacher Action

        #region HttpPost Update Teacher Action
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(Teacher teacher, IFormCollection form)
        {
            if (ModelState.IsValid)
            {
                DbSet<Teacher> dbs = _dbContext.Teacher;
                Teacher tTeach = dbs.Where(mo => mo.TeacherId == teacher.TeacherId).FirstOrDefault();

                DbSet<Class> dbs3 = _dbContext.Class;
                List<Class> lstCls = dbs3.ToList();
                var dbcount = lstCls.Count();

                DbSet<TeacherClassBindDb> dbs2 = _dbContext.TeacherClassBindDb;
                List<TeacherClassBindDb> lstdb2 = dbs2.Where(mo => mo.TeacherId == teacher.TeacherId).ToList();

                List<int> lstoverlap = lstdb2.Select(mo => mo.ClassId).ToList();
                List<int> lstdb3 = dbs2.Select(mo => mo.ClassId).ToList();
                List<int> commonlist = lstoverlap.Intersect(lstdb3).ToList();

                for (var x = 0; x < dbcount; x++)
                {

                    TeacherClassBindDb teacherClassBindDb = new TeacherClassBindDb();
                    var y = x + 1;
                    var classcheck = Convert.ToInt32(form["currAddId" + y]);
                    var radiocheck = Convert.ToInt32(form["Add" + y]);

                    if (commonlist.Contains(classcheck) && radiocheck == -1)
                    {
                        dbs2.Remove(dbs2.Where(mo => mo.TeacherId == teacher.TeacherId && mo.ClassId == y).FirstOrDefault());
                    }
                    else if (commonlist.Contains(classcheck) && radiocheck > 0)
                    {
                        continue;
                    }
                    else if (radiocheck > 0)
                    {
                        if (ModelState.IsValid)
                        {
                            teacherClassBindDb.TeacherId = teacher.TeacherId;
                            teacherClassBindDb.ClassId = radiocheck;
                            dbs2.Add(teacherClassBindDb);

                        }
                    }

                }

                if (tTeach != null)
                {
                    tTeach.Name = teacher.Name;
                    tTeach.MobileNo = teacher.MobileNo;
                    tTeach.Email = teacher.Email;
                    tTeach.Role = teacher.Role;

                    if (_dbContext.SaveChanges() >= 1)
                        TempData["Msg"] = "Teacher updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Teacher not found!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }
        #endregion HttpPost Update Teacher Action

        #region HttpPost Delete Teacher Action
        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<Teacher> dbs = _dbContext.Teacher;
            DbSet<TeacherClassBindDb> dbs2 = _dbContext.TeacherClassBindDb;
            DbSet<TeacherStudentBindDb> dbs3 = _dbContext.TeacherStudentBindDb;

            dbs3.RemoveRange(dbs3.Where(mo => mo.TeacherId == id).ToList());
            _dbContext.SaveChanges();

            dbs2.RemoveRange(dbs2.Where(mo => mo.TeacherId == id).ToList());
            _dbContext.SaveChanges();

            Teacher tTeach = dbs.Where(mo => mo.TeacherId == id)
                                     .FirstOrDefault();

            if (tTeach != null)
            {
                dbs.Remove(tTeach);
                if (_dbContext.SaveChanges() == 1)

C300Project/Views/Teacher/Create.cshtml
@model Teacher

@{
    var b = ViewData["Class"] as List<Class>;
    ViewBag.Title = "Add new teacher";
    int x = 1;
}

@section ScriptSection {

    
    <script>
        function ConfirmCreate() {
            if (confirm("Confirm create Question?") == false) {
                event.preventDefault();
                event.stopPropagation();
                return false;

            }
        }

    </script>
}


    <h2>@ViewData["Title"]</h2>

    <div class="row">
        <div class="col-sm-7">
            <span style="color:red">@ViewData["Msg"]</span><br />
            <form asp-controller="Teacher" asp-action="Create" method="post" class="form-horizontal" role="form">
                <div class="form-horizontal">
                    <partial name="_Teacher" />

                    <div>
                        <table class="table table-bordered table-condensed table-hover table-striped">
                            <tr>
                                <th>Id</th>
                                <th>Class Name</th>
                                <th>Add To Class?</th>
                            </tr>


                            @foreach (var item in @b)

                            {
                                <tr>
                                    <td>
                                        @x
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        <input type="radio" id="rdOption1" value="@item.ClassId" name="@("Add" +x)" /> Yes
                                        <input type="radio" id="rdOption2" value="-1" name="@("Add" +x)" /> No
                                    </td>
                                </tr>
                                x++;
                            }

                        </table>

                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <input type="submit" value="Add" class="btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

C300Project/Views/Teacher/Index.cshtml
@model List<Teacher>

@{
    ViewBag.Title = "Questions";
    int x = 1;
}

@{

}

@section ScriptSection {

    <script>
        function ConfirmDelete() {
            if (confirm("Are you sure you want to delete?") == false) {
                event.preventDefault();
                event.stopPropagation();
                return false;

            }
        }

    </script>
}

<h2>Teacher Database</h2>




<span style="color:red">@TempData["Msg"]</span>
<br />
<p>
    <a asp-controller="Teacher" asp-action="Create">Add New Teacher</a>
</p>
<div class="tab-content" style="margin-top:10px">
    <div>
        <table class="table table-bordered table-condensed table-hover table-striped">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Mobile No</th>
                <th>Email</th>
                <th>Role</th>

                @if (User.IsInRole("Admin"))
                {
                    <th>Added By</th>
                }
                <th>Action</th>
            </tr>
            @foreach (var item in Model)

            {
                <tr>
                    <td>
                        @x
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.MobileNo
                    </td>
                    <td>
                        @item.Email
                    </td>

                    <td>
                        @item.Role
                    </td>

                    @if (User.IsInRole("Admin"))
                    {
                        <td>@item.AddedByNavigation.Name</td>
                    }

                    <td>
                        <a asp-action="Update" asp-route-id="@item.TeacherId" onclick="return ConfirmUpdate()">Update</a>
                        <a asp-action="Delete" asp-route-id="@item.TeacherId" onclick="return ConfirmDelete()">Delete</a>

                    </td>
                </tr>
                x++;
            }


        </table>
    </div>
</div>

C300Project/Views/Teacher/Update.cshtml
@model Teacher

@{
    var b = ViewData["Test"] as List<Class>;
    var c = ViewData["common"] as List<int>;
    ViewBag.Title = "Update Teacher!";
    int x = 1;
}

@section ScriptSection {


<script>
    function ConfirmUpdate() {
        if (confirm("Are you sure you want to delete?") == false) {
            event.preventDefault();
            event.stopPropagation();
            return false;

        }
    }

</script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <span style="color:red">@ViewData["Msg"]</span><br />
        <div class="container">

            <form asp-controller="Teacher" asp-action="Update" method="post" class="form-horizontal" role="form">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label asp-for="TeacherId" class="col-sm-3 control-label">Teacher Id:</label>
                        <div class="col-sm-6">
                            <input asp-for="TeacherId" class="form-control" readonly="readonly" />
                        </div>
                        <div class="has-error">
                            <span asp-validation-for="TeacherId" class="text-danger"></span>
                        </div>
                    </div>
                    <partial name="_Teacher" />

                    <div>
                        <table class="table table-bordered table-condensed table-hover table-striped">
                            <tr>
                                <th>Id</th>
                                <th>Class Name</th>
                                <th>Add To Class?</th>
                            </tr>


                            @foreach (var item in @b)

                            {
                                <tr>
                                    <td>
                                        @x
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    @if (c.Contains(item.ClassId))
                                    {
                                <td>
                                    <input name="@("currAddId" +x)" value="@item.ClassId" hidden="hidden" />
                                    <input type="radio" id="rdOption1" value="@item.ClassId" name="@("Add" +x)" checked="checked" /> Yes
                                    <input type="radio" id="rdOption2" value="-1" name="@("Add" +x)" /> No
                                </td>

                                    }
                                    else
                                    {
                                <td>
                                    <input name="@("currAddId" +x)" value="@item.ClassId" hidden="hidden" />
                                    <input type="radio" id="rdOption1" value="@item.ClassId" name="@("Add" +x)" /> Yes
                                    <input type="radio" id="rdOption2" value="-1" name="@("Add" +x)" /> No
                                </td>
                                    }

                                </tr>
                                x++;
                            }

                        </table>

                    </div>


                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <input type="submit" value="Update" class="btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
 </div>